% --- Создается легенда после выбора цели, зависимо от работающих на экране
% данных(ПОИ или Шумы)
function makeLegendAfterListbox(handles)
dimentionValue = get(handles.togglebutton4,'Value');

if (dimentionValue == 0)
    realPlot = evalin('base','realPlot');
    realIndex = evalin('base','realIndex');
    voiPlot = evalin('base','voiPlot');
    voiIndex = evalin('base','voiIndex');
    hypoPlot = evalin('base','hypoPlot');
    hypoIndex = evalin('base','hypoIndex');
    
    contents = get(handles.popupmenu1, 'Value');
    switch contents
        case 1
            chPoi = get(handles.checkbox4,'Value');
            chNoize = get(handles.checkbox8,'Value');
            chStrob = get(handles.checkbox12,'Value');
            if(chPoi == 0 && chNoize == 0 && chStrob == 0)
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate]);
            end
            
            if(chPoi == 1 && chNoize == 0 && chStrob == 0)
                poiPlot = evalin('base','poiPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    poiPlot.ch5,poiPlot.ch6,poiPlot.ch7] );
            end
            
            if(chPoi == 0 && chNoize == 1 && chStrob == 0)
                noizePlot = evalin('base','noizePlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    noizePlot.ch9,noizePlot.ch10,noizePlot.ch11]);
            end
            if(chNoize == 1 && chPoi == 1 && chStrob == 0)
                noizePlot = evalin('base','noizePlot');
                poiPlot = evalin('base','poiPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    poiPlot.ch5,poiPlot.ch6,poiPlot.ch7,...
                    noizePlot.ch9,noizePlot.ch10,noizePlot.ch11]);
            end
            
            if(chPoi == 0 && chNoize == 0 && chStrob == 1)
                strobPlot = evalin('base','strobPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    strobPlot.ch13,strobPlot.ch14,strobPlot.ch15]);
            end
            
            if(chPoi == 1 && chNoize == 0 && chStrob == 1)
                poiPlot = evalin('base','poiPlot');
                strobPlot = evalin('base','strobPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    poiPlot.ch5,poiPlot.ch6,poiPlot.ch7,...
                    strobPlot.ch13,strobPlot.ch14,strobPlot.ch15]);
            end
            
            if(chPoi == 0 && chNoize == 1 && chStrob == 1)
                noizePlot = evalin('base','noizePlot');
                strobPlot = evalin('base','strobPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    noizePlot.ch9,noizePlot.ch10,noizePlot.ch11,...
                    strobPlot.ch13,strobPlot.ch14,strobPlot.ch15]);
            end
            if(chNoize == 1 && chPoi == 1 && chStrob == 1)
                noizePlot = evalin('base','noizePlot');
                strobPlot = evalin('base','strobPlot');
                poiPlot = evalin('base','poiPlot');
                legend([realPlot(realIndex).ch1.coordinate,realPlot(realIndex).ch2.coordinate,...
                    realPlot(realIndex).ch3.coordinate,...
                    voiPlot(voiIndex).ch1.coordinate,voiPlot(voiIndex).ch2.coordinate,...
                    voiPlot(voiIndex).ch3.coordinate,...
                    hypoPlot(hypoIndex).ch1.coordinate,hypoPlot(hypoIndex).ch2.coordinate,...
                    hypoPlot(hypoIndex).ch3.coordinate,...
                    poiPlot.ch5,poiPlot.ch6,poiPlot.ch7,...
                    noizePlot.ch9,noizePlot.ch10,noizePlot.ch11,...
                    strobPlot.ch13,strobPlot.ch14,strobPlot.ch15]);
            end
        case 2
            legend([realPlot(realIndex).ch1.speed,realPlot(realIndex).ch2.speed,...
                realPlot(realIndex).ch3.speed,...
                 voiPlot(voiIndex).ch1.speed,voiPlot(voiIndex).ch2.speed,...
                 voiPlot(voiIndex).ch3.speed,...
                 hypoPlot(hypoIndex).ch1.speed,hypoPlot(hypoIndex).ch2.speed,...
                 hypoPlot(hypoIndex).ch3.speed]);
        case 3
            legend([realPlot(realIndex).ch1.acceleration,realPlot(realIndex).ch2.acceleration,...
                realPlot(realIndex).ch3.acceleration,...
                voiPlot(voiIndex).ch1.acceleration,voiPlot(voiIndex).ch2.acceleration,...
                voiPlot(voiIndex).ch3.acceleration,...
                hypoPlot(hypoIndex).ch1.acceleration,hypoPlot(hypoIndex).ch2.acceleration,...
                hypoPlot(hypoIndex).ch3.acceleration]);     
    end
else
    Real3dPlot = evalin('base','Real3dPlot');
    RealEnd3dPlot = evalin('base','RealEnd3dPlot');
    realIndex = evalin('base','realIndex');
    Voi3dPlot = evalin('base','Voi3dPlot'); 
    VoiEnd3dPlot = evalin('base','VoiEnd3dPlot');
    voiIndex = evalin('base','voiIndex');
    Hypo3dPlot = evalin('base','Hypo3dPlot');
    HypoEnd3dPlot = evalin('base','HypoEnd3dPlot');
    hypoIndex = evalin('base','hypoIndex');

    chPoi = get(handles.checkbox4,'Value');
    chNoize = get(handles.checkbox8,'Value');
    if(chPoi == 0 && chNoize == 0)
        legend([Real3dPlot(realIndex),RealEnd3dPlot(realIndex)...
            Voi3dPlot(voiIndex),VoiEnd3dPlot(voiIndex)...
            Hypo3dPlot(hypoIndex),HypoEnd3dPlot(hypoIndex)]);
    end
            
    if(chPoi == 1 && chNoize == 0)
        poi3dPlot = evalin('base','poi3dPlot');
        legend([Real3dPlot(realIndex),RealEnd3dPlot(realIndex)...
            Voi3dPlot(voiIndex),VoiEnd3dPlot(voiIndex)...
            Hypo3dPlot(hypoIndex),HypoEnd3dPlot(hypoIndex),...
            poi3dPlot] );
    end
    if(chPoi == 0 && chNoize == 1)
        Noize3dPlot = evalin('base','Noize3dPlot');
        legend([Real3dPlot(realIndex),RealEnd3dPlot(realIndex)...
            Voi3dPlot(voiIndex),VoiEnd3dPlot(voiIndex)...
            Hypo3dPlot(hypoIndex),HypoEnd3dPlot(hypoIndex),...
            Noize3dPlot]);
    end
    if(chNoize == 1 && chPoi == 1)
        Noize3dPlot = evalin('base','Noize3dPlot');
        poi3dPlot = evalin('base','poi3dPlot');
        legend([Real3dPlot(realIndex),RealEnd3dPlot(realIndex)...
            Voi3dPlot(voiIndex),VoiEnd3dPlot(voiIndex)...
            Hypo3dPlot(hypoIndex),HypoEnd3dPlot(hypoIndex),...
            poi3dPlot,Noize3dPlot]);
    end      
end